### PR TITLE
Complete message on error

### PR DESCRIPTION
**Pull request by waystilos**
Completing the error message in the except block. 

As of now, if a file cannot be processed, it'll keep looping back to be processed again. This will complete the message so it doesn't loop back. Also, we log which file is error'd out.

### CODE REVIEW

**Comment by senthilkungumaraj** [comment]
@waystilos We should not complete failed message and instead should abandon the message as was the case previously. I think the scenario of this PR is still valid, and we need to address this. But we may want to still abandon the message and in the topic set the max delivery retries. I believe if we configure this, the message will then end up in dead letter queue. So, we don't have to keep processing a failed message again and again.

**Comment by waystilos** [comment]
> @waystilos We should not complete failed message and instead should abandon the message as was the case previously. I think the scenario of this PR is still valid, and we need to address this. But we may want to still abandon the message and in the topic set the max delivery retries. I believe if we configure this, the message will then end up in dead letter queue. So, we don't have to keep processing a failed message again and again.

@senthilkungumaraj That sounds good. I changed it back to `abandon_message` and set the max delivery count to 2. Let me know if the maxDeliveryCount should be a different number.

**Review by senthilkungumaraj — APPROVED** [review]

**Comment by senthilkungumaraj** [comment]
> > @waystilos We should not complete failed message and instead should abandon the message as was the case previously. I think the scenario of this PR is still valid, and we need to address this. But we may want to still abandon the message and in the topic set the max delivery retries. I believe if we configure this, the message will then end up in dead letter queue. So, we don't have to keep processing a failed message again and again.
> 
> @senthilkungumaraj That sounds good. I changed it back to `abandon_message` and set the max delivery count to 2. Let me know if the maxDeliveryCount should be a different number.

2 retries should be good. We can get user feedback if we need to increase it further in future. But we can go with 2 for now.

**Comment by senthilkungumaraj** [comment]
@waystilos Quick question - Is this change deployed and validated?

**Review by mandarinamdar — APPROVED** [review]

**Comment by waystilos** [comment]
> @waystilos Quick question - Is this change deployed and validated?

@senthilkungumaraj Sorry for the delay in message. I was investing how this works in our deployment. It works when I test it on a private instance of mine, outside of the VNET. However, when I test it in our deployment, the message does get abandoned after 2 tries but doesn't move to the DLQ. Still not sure why it wouldn't work in our solution.

**Pull request merged**
